# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-04-14 17:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapa', '0002_auto_20220414_1606'),
    ]

    operations = [
        migrations.RenameField(
            model_name='elemento',
            old_name='geometria',
            new_name='draw',
        ),
    ]
