# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-04-14 17:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapa', '0003_auto_20220414_1738'),
    ]

    operations = [
        migrations.RenameField(
            model_name='elemento',
            old_name='draw',
            new_name='geometria',
        ),
    ]
