# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-04-14 18:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapa', '0005_elemento_estilo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elemento',
            name='estilo',
            field=models.CharField(max_length=100000),
        ),
    ]
