# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-04-14 19:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapa', '0006_auto_20220414_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='elemento',
            name='fill',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='elemento',
            name='font',
            field=models.CharField(default='', max_length=100000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='elemento',
            name='function',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='elemento',
            name='stroke',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='elemento',
            name='type',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
